### PR TITLE
Full rework of Ethernet HAL driver

### PR DESCRIPTION
**Pull request by ALABSTM**
The reworked Ethernet HAL driver brings multiple changes and a compatibility break vs. previous Ethernet HAL driver.
Main changes are listed here:
- Add support for PTP and ARP
- Rework packets reception and buffers allocation for better integration and performance
- Rework packets transmission and buffers allocation (using interrupts instead of polling and prevent packets lock during transmission)
- Enhance DMA management
- Decouple Ethernet HAL driver from PHY driver
- Enhance maximum throughput in RX (94Mbs) and TX (92Mbs)
- Enhance footprint (new driver size is 6% less than previous driver)
- Full integration with LwIP (with and without FreeRTOS) and NetXDuo with ThreadX.
- MISRA-C 2012, code coverage analysis, static code analysis and robustness validation added.

### CODE REVIEW

**Comment by Jovan-ux** [comment]
Where the applications are located? Cannot find'em.
Thx, KR Jo

**Comment by Jovan-ux** [comment]
Actually you would not provide any applications for ethernet in the main repo https://github.com/STMicroelectronics/STM32CubeH7 if ethernet driver is not published officially, would you? No changes regarding demo applications/projects found in H7 firmware package released...

Would appreciate if you can give me a hint...
Thx,KR jo

**Comment by ALABSTM** [comment]
Hi @Arni1115 and @Jovan-ux,

Please excuse this delayed reply. Indeed, The applications using this new ETH HAL driver have not been published yet. They shall be in the [STM32CubeH7](https://github.com/STMicroelectronics/STM32CubeH7) repo. Their publication is planned in a couple of weeks.

In the meanwhile, the idea is to provide the new driver before that date, via this pull-request, to allow our users to test it with their own applications.

As for the updated applications, I can check with our development teams whether it is possible to provide them the same way (via a pull-request) before the official publication date. I will get back to you as soon as I have their feedback. As this period corresponds to the end-of-year leaves, this might take some time. Thank you in advance for your patience and comprehension.

Regarding why this pull-request is not rebased on top of the new tagged commit v1.10.1, as said earlier, the main purpose is to make the driver available before the official publication date, rather than to maintain the pull-request and to rebase it each time a new commit is added (after going through resolving any eventual conflicts). After all, this reworked driver will be officially published soon.

I hope this answers your questions. Do not hesitate otherwise.

With regards,

**Comment by ALABSTM** [comment]
Hi all,

Updated applications using the new ETH HAL driver have just been published via pull-request [STM32CubeH7#195](https://github.com/STMicroelectronics/STM32CubeH7/pull/195) (including the new ETH HAL driver too). LwIP applications are provided for the following boards and can be tailored for the others:
* NUCLEO-H723ZG
* NUCLEO-H743ZI
* STM32H735G-DK
* STM32H743I-EVAL

Please feel free to give your feedback and report any point you would find worth to mention. Happy end-of-year 2021 and a happier 2022.

With regards,

**Comment by ra1u** [comment]
Issues remains with error handling.

No all errors are handled in [stm32h7xx_hal_eth.c#L1894-L1895](https://github.com/STMicroelectronics/STM32CubeH7/blob/0c3a06c18bd2a87b006a84f997f2b0b56d97a113/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_eth.c#L1894-L1895)  Particularly not _ETH_DMACSR_ERI_ and _ETH_DMACSR_TBU_. This results lot of interrupts as they are not handled.

In general errors are not handled at all, but are just suppressed. 

For example. There is deadlock in tx, partially due to  missing return value/error checking on _HAL_ETH_Transmit_IT_ [ethernetif.c#L313-L317](https://github.com/STMicroelectronics/STM32CubeH7/blob/0c3a06c18bd2a87b006a84f997f2b0b56d97a113/Projects/NUCLEO-H723ZG/Applications/LwIP/LwIP_HTTP_Server_Netconn_RTOS/Src/ethernetif.c#L313-L317)

This becomes noticable when link goes down [ethernetif.c#L636](https://github.com/STMicroelectronics/STM32CubeH7/blob/master/Projects/NUCLEO-H723ZG/Applications/LwIP/LwIP_HTTP_Server_Netconn_RTOS/Src/ethernetif.c#L636)
Result is that since interrupts and transfer is suddenly disabled, we get into deadlock.

There is also no synchronization over this handle and its members for example _EthHandle.gState._

**Pull request merged**
